### PR TITLE
WIP: 2.0.dev0

### PR DESCRIPTION
**Pull request by ashcrow**
Merging of 2.0 branch

cc @JohnAD

### CODE REVIEW

**Comment by JohnAD** [comment]
Awesome.

Regarding the URL, yes, for a system with multiple hosts, storing the full URL would be very useful. I'll leave it as is.

I've done a crude rough draft of the video; still have audio sync and continuity problems with the edit. Anyway, I kind of meander a bit on the "why flask-track-usage" section. Any suggestions to tighten it up?

It is still unlisted, but you can reach it with the direct link:

https://youtu.be/HBbkjouL6Uo

John

**Comment by ashcrow** [comment]
Blog post about upcoming changes and testing: https://stevemilner.org/2018/04/25/flask-track-usage-2-0-0-testing/

**Comment by JohnAD** [comment]
I've done the final video. It is unlisted still. I'll make it public when 2.0 makes it to PyPi. (The version shown will not work with 1.x because it demo storing in both PostgreSQL and MongoEngine at the same time.)

Unllisted link:
   https://youtu.be/r1wL0FVeLmA

**Comment by ashcrow** [comment]
Awesome! I'm going to push it out to pypi sometime next week unless someone finds a bug.

**Comment by JohnAD** [comment]
Just following up. Did you see my note about the `ip_info` field in the other pull request. Would you mind adding another alembic change for `2.0` increasing the field size? Perhaps to 512 or 1024 characters?

Any negative feedback on the changes?

**Comment by ashcrow** [comment]
@JohnAD I'll make another alembic update to increase ``ip_info`` to 1024. Just reviewed the PR and had some minor changes requested.

**Pull request closed without merging**
