### PR TITLE
Include X-Forwarded-For as well as remote_addr

### PR DESCRIPTION
**Pull request by jamylak**
"Since it is easy to forge an X-Forwarded-For field the given information should be used with care. The last IP address is always the IP address that connects to the last proxy, which means it is the most reliable source of information. X-Forwarded-For data can be used in a forward or reverse proxy scenario.

Just logging the X-Forwarded-For field is not always enough as the last proxy IP address in a chain is not contained within the X-Forwarded-For field, it is in the actual IP header. A web server should log BOTH the request's source IP address and the X-Forwarded-For field information for completeness."

Why not log both instead of guessing? Would love to hear feedback on this.

### CODE REVIEW

**Comment by ashcrow** [comment]
I guess there isn't really a reason to only log one! I'll take a look at the patch soon. Thanks!

**Comment by jamylak** [comment]
@ashcrow Also freegeoip isn't working. I changed mine to use GeoIp but i don't know which solution you think is best to switch to.

**Comment by ashcrow** [comment]
Looks like Freegeoip service is returning bad gateway. I'll see if I can contact the service owner and find out if it's going offline or just encountering an outage.

**Comment by ashcrow** [comment]
I spoke with the guy who runs the FreeGeopIP service and there is currently some datacenter issues but it should be back. However, this highlighted the reliance on one geopip service so I created #19. @jamylak would you mind sharing that you changed to get GeoIP working? I'd be more than happy to include it in the next release!

**Comment by ashcrow** [comment]
I've also created #20 for the header related update.

**Comment by ashcrow** [comment]
The CI failure looks to be pep8 related. I'll pull and fix in a follow on for 1.1.0.

**Comment by ashcrow** [comment]
https://github.com/ashcrow/flask-track-usage/commit/d024ef004c5380d6ed0ccca095a5927ed45ed8c6

**Pull request closed without merging**
